version: '3.8'
services:
  speech-api:
    build: .
    ports:
      - "8010:8010"
    volumes:
      - ./files:/app/files
    environment:
      - FILE_STORAGE=/app/files
    restart: unless-stopped
